-- MySQL Script generated by MySQL Workbench
-- ven. 15 nov. 2019 16:17:20 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `surnamePerson` VARCHAR(45) NULL,
  `firstnamePerson` VARCHAR(45) NULL,
  `pseudoPerson` VARCHAR(45) NULL,
  `emailPerson` VARCHAR(45) NULL,
  `passwordPerson` VARCHAR(255) NULL,
  `dateRegistrationPerson` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `typePerson` VARCHAR(45) NULL DEFAULT 'Member',
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `titleArticle` VARCHAR(255) NULL,
  `subtitleArticle` VARCHAR(45) NULL,
  `contentArticle` TEXT NULL,
  `dateCreationArticle` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `person_idPerson` INT NOT NULL,
  PRIMARY KEY (`idArticle`, `person_idPerson`),
  INDEX `fk_article_personne1_idx` (`person_idPerson` ASC),
  CONSTRAINT `fk_article_personne1`
    FOREIGN KEY (`person_idPerson`)
    REFERENCES `person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comment` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `authorComment` VARCHAR(45) NULL,
  `contentComment` TEXT NULL,
  `dateComment` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `article_idArticle` INT NOT NULL,
  `validate` VARCHAR(45) NULL DEFAULT 'En attente',
  PRIMARY KEY (`idComment`, `article_idArticle`),
  INDEX `fk_commentaire_article_idx` (`article_idArticle` ASC),
  CONSTRAINT `fk_commentaire_article`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
